---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JCY.
--- DateTime: 2018/10/19 11:54
---

---@class IGameState
local IGameState = {}

IGameState.StateEnum = 0
---@type FSM
IGameState.FSM = nil

function IGameState.OnEnter()

end

function IGameState.Update()

end

function IGameState.OnExit()

end

return IGameState