---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JCY.
--- DateTime: 2018/10/19 14:01
---

---@class FightState:IGameState 主界面游戏配置的相关信息
local FightState = {}
local this = FightState;

function FightState.OnEnter()

end

function FightState.Update()

end

function FightState.OnExit()

end

return FightState;