---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JCY.
--- DateTime: 2018/10/19 13:57
---

---@class GameDeployState:IGameState 主界面游戏配置的相关信息,详细操作页面相关
local GameDeployState = {}
local this = GameDeployState;

function GameDeployState.OnEnter()

end

function GameDeployState.Update()

end

function GameDeployState.OnExit()

end

return GameDeployState;