---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JCY.
--- DateTime: 2018/10/19 15:39
---

---@class IdleState:IGameState 主界面游戏配置的相关信息
local IdleState = {}
local this = IdleState;

function IdleState.OnEnter()

end

function IdleState.Update()

end

function IdleState.OnExit()

end

return IdleState;