---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JCY.
--- DateTime: 2018/10/19 14:00
---

---@class LoadingState:IGameState 主界面游戏配置的相关信息
local LoadingState = {}
local this = LoadingState;

function LoadingState.OnEnter()

end

function LoadingState.Update()

end

function LoadingState.OnExit()

end

return LoadingState;