---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JCY.
--- DateTime: 2018/10/19 14:20
---

GameStateType = {
    Idle = 0, --暂定默认状态
    LoginState = 1, --登录界面状态
    GameDeployState = 2, --游戏中选择配置的状态
    LoadingState = 3, --读条状态
    FightState = 4, --战斗界面状态
}