---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JCY.
--- DateTime: 2018/10/17 21:15
---

---@class DefultSaveConfig
DefultSaveConfig = {}

DefultSaveConfig.SettingDefultConfig = {
    ---@type number 玩家保存音量设置
    MusicPriority = 100,
    ---@type number 玩家保存的音乐音质 感觉没卵用
    MusicQuality = 100,
    ---@type table 当前玩家启用的语言
    CurrLanguage = DataConst.CurLanguage.Cn,
    ---@type table 当前玩家保存的画质质量，暂定6个固定档位
    RenderQuality = DataConst.RenderQuality.Medium,
}

return DefultSaveConfig;
