---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JCY.
--- DateTime: 2018/10/18 21:37
---

---@class RegistModel 注册数据模型
local RegistModel = {}
local this = RegistModel;

---@type table 周边数据模型
RegistModel.PerimeterModels = {}
---@type table 玩家游戏数据模型
RegistModel.GameContentModels = {}

function RegistModel.Init()
    this.PerimeterModels["PlayerDataModel"] = require("Game.Main.Model.PlayerDataModel")
    this.PerimeterModels["SettingModel"] = require("Game.Main.Model.SettingModel")

    this.GameContentModels["BattleModel"] = require("Game.Main.Model.BattleModel")
    this.GameContentModels["SoliderListModel"] = require("Game.Main.Model.SoliderListModel")
    this.GameContentModels["TankListModel"] = require("Game.Main.Model.TankListModel")

    --this.ModelsList["FightModel"] = require("Game.Model.FightModel")
end

return RegistModel