---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JCY.
--- DateTime: 2018/10/16 11:54
---
local FightCfg = require("Game.Model.Data.FightCfg")
local FightData = require("Game.Model.Data.FightData")

---@class FightModel:ISaveLoad
local FightModel = {}
local this = FightModel;

---@type FightCfg[] 配置战斗信息
FightModel.FightCfg = {}
---@type FightData[] 配置战斗信息
FightModel.FightData = {}

function FightModel.Load(info)
    if info ~= nil then
        for k, v in pairs(info) do
            local temp = FightData.new()
            temp:UpdateInfo(v)
            table.insert(this.FightData, temp);
        end
    end
    --for k, v in pairs(configInfo) do
    --    local temp = FightCfg.new();
    --    temp:UpdateInfo(v);
    --    table.insert(this.FightCfg, temp);
    --end
end

function FightModel.Save()
    return this.FightData;
end

return FightModel;