---
--- 每个存档的数据信息
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JCY.
--- DateTime: 2018/10/11 10:01
---

local SaveData = require("Game.Main.Model.Data.SaveData")
local RegistModel = require("Game.Config.RegistModel")

---@class SaveModel:ISaveLoad
local SaveModel = {}
local this = SaveModel;

---@type SaveData 保存的数据
SaveModel.SaveData = {}
---@type number 自动存档ID
SaveModel.AutoSaveID = -1;

---玩家没有玩过游戏时候第一次调用
function SaveModel.CreatNewSave()
    RegistModel.Init()
    this.SaveData = SaveData.new()
end

function SaveModel.Load()
    RegistModel.Init()
    local tempData = JsonDataMgr.GetAllSaveJosnData(DataConst.SaveName.SaveData);
    this.SaveData = SaveData.new()
    this.SaveData:SetPlayerData(tempData.PlayerData);
    this.SaveData:SetSettingData(tempData.SettingData);
    this.SaveData:SetAutoData(tempData.AutoSave);
    this.SaveData:SetSaveDataList(tempData.SaveDataList);
    this.LoadSave()
end

function SaveModel.LoadSave()
    for k, v in pairs(RegistModel.PerimeterModels) do
        v.Load(this.SaveData);
    end
end

function SaveModel.LoadGameSave(id)
    if id == this.AutoSaveID then
        for k, v in pairs(RegistModel.GameContentModels) do
            v.Load(this.SaveData.AutoSave);
        end
        return ;
    end
    for k, v in pairs(RegistModel.GameContentModels) do
        v.Load(this.SaveData.SaveDataList[tonumber(id)]);
    end
end

---@return boolean 判断是否还有位置存储
function SaveModel.IsSave()
    if this.GetSaveDataListCount() < 10 then
        return true;
    else
        return false;
    end
end

function SaveModel.GetSaveDataListCount()
    return #this.SaveData.SaveDataList;
end

---保存自动存档
function SaveModel.SaveAutoData()
    this.SaveData:UpdateAutoSave()
    for k, v in pairs(RegistModel.PerimeterModels) do
        v.Save();
    end
    for k, v in pairs(RegistModel.GameContentModels) do
        v.Save();
    end
    this.SaveData:CleanTemp()
    this.DoSave()
end

---@param id 存档id
---@param saveName 存档名字
function SaveModel.Save(id, saveName)
    this.SaveData:SetDataList(id, saveName)
    for k, v in pairs(RegistModel.PerimeterModels) do
        v.Save();
    end
    for k, v in pairs(RegistModel.GameContentModels) do
        v.Save();
    end
    this.SaveData:CleanTemp()
    this.DoSave()
end

---存档动作
function SaveModel.DoSave()
    JsonDataMgr.DoSave(DataConst.SaveName.SaveData, this.SaveData)
end

return SaveModel;