---
---玩家的游戏设置信息
---Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JCY.
--- DateTime: 2018/10/10 14:39
---

local SettingData = require("Game.Main.Model.Data.SettingData")
local SaveModel = require("Game.Main.Model.SaveModel")

---@class SettingModel:ISaveLoad
local SettingModel = {}
local this = SettingModel;

---@type table 设置数据
SettingModel.SettingData = {};

function SettingModel.Load(info)
    this.SettingData = SettingData.new();
    if info ~= nil then
        this.SettingData:UpdateInfo(info.SettingData)
    end
end

function SettingModel.Save()
    SaveModel.SaveData:SetSettingData(this.SettingData)
end

function SettingModel.SetMusicPriority(index)
    this.SettingData:SetMusicPriority(index);
end

function SettingModel.SetMusicQuality(index)
    this.SettingData:SetMusicQuality(index);
end

function SettingModel.SetCurLanguage(index)
    this.SettingData:SetCurLanguage(index);
end

function SettingModel.SetRenderQuality(index)
    this.SettingData:SetRenderQuality(index);
end

function SettingModel.GetMusicPriority()
    return this.SettingData.MusicPriority;
end

function SettingModel.GetMusicQuality()
    return this.SettingData.MusicQuality;
end

function SettingModel.GetCurrLanguage()
    return this.SettingData.CurrLanguage;
end

function SettingModel.GetRenderQuality()
    return this.SettingData.RenderQuality;
end

return SettingModel;