---
---编组
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JCY.
--- DateTime: 2018/10/15 20:30
---
local BattleTeamData = require("Game.Main.Model.Data.BattleTeamData")
local SoliderListModel = require("Game.Main.Model.SoliderListModel")
local TankListModel = require("Game.Main.Model.TankListModel")
local SaveModel = require("Game.Main.Model.SaveModel")

---@class TeamModel:ISaveLoad
local TeamModel = {}
local this = TeamModel;

---@type BattleTeamData[] 编队列表列表
TeamModel.BattleTeam = {}

function TeamModel.Load()
    for k, v in pairs(SoliderListModel.GetSoliderList()) do
        if v.BindTankID ~= -1 then
            local temp = BattleTeamData.new( )
            temp:UpdateInfo(v.ID, v.BindTankID)
            table.insert(this.BattleTeam, temp);
        end
    end
end

function TeamModel.Save()
    SaveModel.SaveData:SetBattleTeamData(this.BattleTeam)
end

function TeamModel.GetBattleTeamInfo()
    return this.BattleTeam;
end

---@return 返回未编队的士兵
function TeamModel.GetNoTeamSoliderList()
    local returnTemp = {};
    for k, v in pairs(SoliderListModel.GetSoliderList()) do
        if v.BindTankID == -1 then
            table.insert(returnTemp, v);
        end
    end
end

---@return 返回未编队的坦克
function TeamModel.GetNoTeamTankList()
    local temp = {};
    for k, v in pairs(SoliderListModel.GetSoliderList()) do
        if v.BindTankID > -1 then
            table.insert(temp, v.BindTankID);
        end
    end
    local tankList = TankListModel.GetTankList();
    for k, v in pairs(temp) do
        for a, b in pairs(tankList) do
            if b.TankID == v then
                b.Count = b.Count - 1;
            end
        end
    end
    return tankList
end

function TeamModel.SetNewTeam(soliderID, tankID)
    local temp = BattleTeamData.new( )
    temp:UpdateInfo(soliderID ,tankID)
    table.insert(this.BattleTeam, temp);
    SoliderListModel.SetSoliderBindTankID(soliderID, tankID)
end

function TeamModel.RemoveTeam(soliderID, tankID)
    for i = #this.BattleTeam, 1, -1 do
        if this.BattleTeam[i].SoliderID == soliderID then
            table.remove(this.BattleTeam, i);
            SoliderListModel.SetSoliderBindTankID(soliderID, tankID)
        end
    end
end










-----@param id 当前战役的ID
--function TeamModel.SetValue(data, id)
--    if data == nil then
--        return
--    end
--    for k, v in pairs(data) do
--        table.insert(this.BattleTeam, BattleTeamData.new(v));
--    end
--    for k, v in pairs(this.BattleTeam) do
--        if v.ID == id then
--            this.BattleTeamData = BattleTeamData.new(v)
--        end
--    end
--end

--function TeamModel.AddRecurit(recurit)
--    for k, v in pairs(recurit.SoliderList) do
--        table.insert(this.NoTeamSolider, v);
--    end
--    for k, v in pairs(recurit.TankList) do
--        table.insert(this.NoTeamTank, v);
--    end
--end
--
--function TeamModel.GetBattleTeamByID(id)
--    for k, v in pairs(this.BattleTeam) do
--        if v.ID == id then
--            this.BattleTeamData = BattleTeamData.new(v)
--        end
--    end
--end
--
-----@param id 对应的战役ID的编队信息
--function TeamModel.GetBattleTeamByID()
--    return this.BattleTeamData.Team;
--end
--
-----@param id 对应的战役ID的未编队士兵
--function TeamModel.GetBattleNoTeamSoliderByID()
--    return this.BattleTeamData.NoTeamSolider;
--end
--
-----@param id 对应的战役ID的未编队坦克列表
--function TeamModel.GetBattleNoTeamTankByID()
--    return this.BattleTeamData.NoTeamTank;--{{ID:1,Count:2},{...}}
--end
--
----设置新的编组
-----@param soliderID 士兵在未编组中的
-----@param id 士兵信息中对应坦克的id坦克在未编组中的
--function TeamModel.SetNewTeam(soliderID, id)
--    local temp = {};
--    for k, v in pairs(this.NoTeamSolider) do
--        if v.ID == soliderID then
--            v.BindTankID = id;--设置绑定ID
--            temp.Solider = v;
--            table.remove(this.NoTeamSolider, k);--删除在没有编组的表中数据
--            table.insert(this.Team, temp);
--            for a, b in pairs(this.NoTeamTank) do
--                if b.ID == id then
--                    b.Count = b.Count - 1;
--                end
--            end
--        end
--    end
--    if soliderID == nil then
--
--    end
--    if id == nil then
--
--    end
--end

return TeamModel;