---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JCY.
--- DateTime: 2018/10/16 11:41
---

---@class BattleCfg
local BattleCfg = class("BattleCfg")

------------------------------------
---@type number 战役ID
BattleCfg.Battle_ID = 0;
---@type string 坦克型号
BattleCfg.TankIDList = "";
---@type string 坦克消耗
BattleCfg.TankUseList = "";
---@type number 士兵最大数量
BattleCfg.SoliderMaxCount = 0;
---@type number 坦克最大数量
BattleCfg.TankMaxCount = 0;
---@type string 战役描述
BattleCfg.Des = "";
---@type number 坦克ID最大数量
BattleCfg.TankIDMaxCountList =0;
------------------------------------

function BattleCfg:ctor(info)
    self.Battle_ID = info.Battle_ID;
    self.SoliderMaxCount = info.SoliderMaxCount;
    self.TankIDList = info.TankIDList;
    self.TankUseList = info.TankUseList;
    self.TankMaxCount = info.TankMaxCount;
    self.Des = info.Des;
    self.TankIDMaxCountList = info.TankIDMaxCountList;
end

return BattleCfg;
