---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JCY.
--- DateTime: 2018/10/16 19:12
---

---@class BattleData
local BattleData = class("BattleData")

---@type number 判断战役是否完成
BattleData.State = 0;
---@type number 战役ID
BattleData.ID = 0;

function BattleData:ctor()
    self.ID = 0;
    self.State = 0;
end

function BattleData:UpdataInfo(info)
    self.ID = info.ID;
    self.State = info.State;
end

function BattleData:UpdataNew(id)
    self.ID = id;
    self.State = 0;
end

return BattleData
