---
--- 具体每场战斗信息
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JCY.
--- DateTime: 2018/10/11 13:38
---

---@class FightCfg 战役中具体的每场战斗数据
local FightCfg = class("FightCfg");

---@type number 战斗的编号
FightCfg.ID = 0;
---@type string 战斗的名字
FightCfg.Name = 0;
---@type number 战斗的难度系数
FightCfg.Difficulty = 0;
---@type string 战斗的描述
FightCfg.Dec = 0;
---@type number 战斗的图片
FightCfg.Pic = 0;
---@type table 战斗的位置
FightCfg.Pos = {};
---@type number 下一场战斗的编号
FightCfg.NextIndex = {};
----------------------------------------------
-----@type boolean 是否完成本次战斗
--FightCfg.IsComplete = false

function FightCfg:ctor()
    self.ID = id;
    self.Name = 0;
    self.Difficulty = 0;
    self.Dec = 0;
    self.Pic = 0;
    self.Pos = {};
    self.NextIndex = {};
end

function FightCfg:UpdateInfo(info)
    self.ID = info.ID;
    self.Name = info.Name;
    self.Difficulty = info.Difficulty;
    self.Dec = info.Dec;
    self.Pic = info.Pic;
    self.Pos = info.Pos;
    self.NextIndex = info.NextIndex;
end

return FightCfg;