---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JCY.
--- DateTime: 2018/10/18 9:26
---

---@class FightData
local FightData = class("FightData")

---@type number 战斗ID
FightData.ID = 0;
---@type number 战斗是否完成
FightData.State = 0;--0未完成

function FightData:ctor()
    self.ID = 0;
    self.IsComplete = 0;
end

function FightData:UpdateInfo(info)
    self.ID = info.ID;
    self.IsComplete = info.IsComplete;
end

return FightData;