---
---玩家数据信息
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JCY.
--- DateTime: 2018/10/12 9:46
---

---@class PlayerData
local PlayerData = class("PlayerData")

---@type number 玩家的ID
PlayerData.ID = 0;
---@type string 玩家姓名
PlayerData.Name = "";
---@type string 创建账号时间
PlayerData.CreateTimeStr = "";
---@type int 创建账号时间
PlayerData.CreateTime = 0;
---@type string 最近一次下线时间
PlayerData.RectentQuitTimeStr = "";
---@type int 最近一次下线时间
PlayerData.RectentQuitTime = 0;
---@type string 最近一次打开游戏时间
PlayerData.RectentPlayTimeStr = "";
---@type number 最近一次打开游戏时间
PlayerData.RectentPlayTime = 0;
---@type number 总游戏时间保存
PlayerData.GameTime = 0;
---@type string 最近游戏时间保存
PlayerData.RectentSaveGameTimeStr = "";
---@type number 最近游戏时间保存
PlayerData.RectentSaveGameTime = 0;
---@type number 最近一次玩的存档
PlayerData.RectentPlaySaveID = 0;
---@type number 玩家保存的头像使用number寻找
PlayerData.PlayerIcon = 0;

function PlayerData:ctor()
    self.ID = 0;
    self.Name = "";
    self.CreateTimeStr = "";
    self.CreateTime = 0;
    self.RectentQuitTimeStr = "";
    self.RectentQuitTime = 0;
    self.RectentPlayTimeStr = "";
    self.RectentPlayTime = 0;
    self.GameTime = 0;
    self.RectentSaveGameTimeStr = "";
    self.RectentSaveGameTime = 0;
    self.RectentPlaySaveID = 0;
    self.PlayerIcon = 0;
end

function PlayerData:UpdateInfo(info)
    self.ID = info.ID;
    self.Name = info.Name;
    self.CreateTimeStr = info.CreateTimeStr;
    self.CreateTime = info.CreateTime;
    self.RectentQuitTimeStr = info.RectentQuitTimeStr;
    self.RectentQuitTime = info.RectentQuitTime;
    self.RectentPlayTimeStr = info.RectentPlayTimeStr;
    self.RectentPlayTime = info.RectentPlayTime;
    self.GameTime = info.GameTime;
    self.RectentSaveGameTimeStr = info.RectentSaveGameTimeStr;
    self.RectentSaveGameTime = info.RectentSaveGameTime;
    self.RectentPlaySaveID = info.RectentPlaySaveID;
    self.PlayerIcon = info.PlayerIcon;
end

function PlayerData:InitPlayerData(name)
    self.Name = name;
    self.ID = StrHash(name);
    self.CreateTimeStr = os.date("%Y-%m-%d %H:%M:%S", os.time());
    self.CreateTime = os.time();
    self.GameTime = 0;
    self.PlayerIcon = -1;
end

function PlayerData:SetPlayerIcon(index)
    self.PlayerIcon = index;
end

function PlayerData:SetRectentPlayTime()
    self.RectentPlayTimeStr = os.date("%Y-%m-%d %H:%M:%S", os.time());
    self.RectentPlayTime = os.time();
end

function PlayerData:SetRectentQuitTime()
    self.RectentQuitTimeStr = os.date("%Y-%m-%d %H:%M:%S", os.time());
    self.RectentQuitTime = os.time();
end

function PlayerData:SetRectentSaveGameTime()
    self.RectentSaveGameTimeStr = os.date("%Y-%m-%d %H:%M:%S", os.time());
    self.RectentSaveGameTime = os.time();
end

function PlayerData:SetRectentPlaySaveID(index)
    self.RectentPlaySaveID = index;
end

function PlayerData:SetPlayerIcon(index)
    self.PlayerIcon = index;
end

function PlayerData:SetGameTime()
    self.GameTime = os.date(self.PlayerData.RectentQuitTime - self.PlayerData.CreateTime);
end

return PlayerData;