---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JCY.
--- DateTime: 2018/10/16 21:37
---
local RandomSoliderData = require("Game.Main.Model.Data.RandomSolider ")

---@class RecruitSoliderData
local RecruitSoliderData = class("RecruitSoliderData")

---@type number 士兵ID
RecruitSoliderData.ID = 0;
---@type boolean 是否是老兵
RecruitSoliderData.IsExp = false;
---@type number 绑定坦克ID
RecruitSoliderData.BindTankID = 0;
---@type RandomSoliderData 随机士兵详细信息
RecruitSoliderData.RandomSoliderData = {}

function RecruitSoliderData:ctor()
    self.RandomSoliderData = {};
    self.IsExp = false;
    self.BindTankID = 0;
    self.ID = 0;
end

function RecruitSoliderData:UpdateInfo(info)
    self.RandomSoliderData = info.RandomSoliderData;
    self.IsExp = info.IsExp;
    self.BindTankID = info.BindTankID;
    self.ID = info.ID;
end

function RecruitSoliderData:SetInfo(id, isExp, recruitConfig)
    self.RandomSoliderData = RandomSoliderData.new(recruitConfig)
    self.IsExp = isExp;
    self.BindTankID = -1;
    self.ID = id;
end

function RecruitSoliderData:SetBindTankID(id)
    self.BindTankID = id;
end

return RecruitSoliderData
