---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JCY.
--- DateTime: 2018/10/18 17:14
---

local TankData = require("Game.Main.Model.Data.TankData")

---@class TankInfoData
local TankInfoData = class("TankInfoData")

---@type number 坦克数量
TankInfoData.Count = 0;
---@type number 坦克ID
TankInfoData.ID = 0;
---@type TankData 坦克信息
TankInfoData.TankInfo = {}

function TankInfoData:ctor(id, count)
    self.ID = id;
    self.Count = count;
    self.TankInfo = TankData.new(id);
end

function TankInfoData:UpdateCount(count)
    self.Count = count;
end

return TankInfoData;