---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JCY.
--- DateTime: 2018/10/12 10:21
---

---@class GameSaveData
local GameSaveData = class("GameSaveData")

---@type table 存档招募士兵
GameSaveData.RecruitSoliderData = {};
---@type table 存档招募坦克
GameSaveData.RecruitTankData = {};
---@type table 存档编组数据
GameSaveData.BattleTeamData = {};
---@type table 存档战役
GameSaveData.SaveBattleData = {};
---@type string 存档Name
GameSaveData.SaveName = "";
---@type number 存档ID
GameSaveData.SaveID = 0;
---@type string 创建游戏时间保存
GameSaveData.CreatSaveTime = 0;
---@type string 最近游戏时间保存
GameSaveData.RectentSaveTime = 0;
---@type number 玩家阵营
GameSaveData.Viewer = 0;
---@type number 玩家阵营的头像
GameSaveData.ViewerIcon = 0;
---@type numbe 本存档总游戏时间保存
GameSaveData.SaveAllGameTime = 0;
---@type string 保存的游戏存档所在的版本
GameSaveData.SaveVersion = 0;
---@type table 游戏类型
GameSaveData.GameMode = {};
---@type table 游戏难度
GameSaveData.GameDifficulty = {};
---@type table 游戏扩展DLC
GameSaveData.DLC = {};

function GameSaveData:ctor()
    self.RecruitSoliderData = {};
    self.RecruitTankData = {};
    self.BattleTeamData = {};
    self.SaveBattleData = {};
    self.SaveName = "";
    self.SaveID = -1;
    self.CreatSaveTime = 0;
    self.RectentSaveTime = 0;
    self.Viewer = 0
    self.ViewerIcon = 0;
    self.SaveAllGameTime = 0
    self.SaveVersion = 0
    self.GameMode = 0
    self.GameDifficulty = {}
    self.DLC = {}
end

function GameSaveData:UpdateInfo(info)
    self.RecruitSoliderData = info.RecruitSoliderData;
    self.RecruitTankData = info.RecruitTankData;
    self.BattleTeamData = info.BattleTeamData;
    self.SaveBattleData = info.SaveBattleData;
    self.SaveName = info.SaveName;
    self.SaveID = info.SaveID;
    self.CreatSaveTime = info.CreatSaveTime
    self.RectentSaveTime = info.RectentSaveTime
    self.Viewer = info.Viewer
    self.ViewerIcon = info.ViewerIcon
    self.SaveAllGameTime = info.SaveAllGameTime
    self.SaveVersion = info.SaveVersion
    self.GameMode = info.GameMode
    self.GameDifficulty = info.GameDifficulty
    self.DLC = info.DLC
end

function GameSaveData:UpdateNewSave(name, id)
    self.SaveName = name;
    self.SaveID = id;
    self.CreatSaveTime = os.date("%Y-%m-%d %H:%M:%S", os.time());
    self.RectentSaveTime = os.date("%Y-%m-%d %H:%M:%S", os.time());
end

function GameSaveData:UpdateOldSave()
    self.RectentSaveTime = os.date("%Y-%m-%d %H:%M:%S", os.time());
end

return GameSaveData