---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JCY.
--- DateTime: 2018/10/18 13:34
---

---@class RecruitTankData
local RecruitTankData = class("RecruitTankData")

---@type number 坦克ID
RecruitTankData.TankID = 0;
---@type number 坦克消耗
RecruitTankData.Count = 0;

function RecruitTankData:ctor()
    self.TankID = 0;
    self.Count = 0;
end

function RecruitTankData:UpdateInfo(info)
    self.TankID = info.TankID;
    self.Count = info.Count;
end

function RecruitTankData:GetTankCount()
    return self.Count;
end

function RecruitTankData:SetTankCount(count)
    self.Count = count;
end

function RecruitTankData:SetTankID(tankID)
    self.TankID = tankID
end

return RecruitTankData;