---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JCY.
--- DateTime: 2018/10/18 21:28
---
local GameSaveData = require("Game.Main.Model.Data.GameSaveData")

---@class SaveData
local SaveData = class("SaveData")

---@type GameSaveData 自动存档数据类型
SaveData.AutoSave = {};
---@type PlayerData 玩家基础数据
SaveData.PlayerData = {};
---@type SettingData 玩家游戏设置数据
SaveData.SettingData = {};
---@type GameSaveData[] 玩家手动保存列表
SaveData.SaveDataList = {};
---@type number 自动存档ID
SaveData.AutoSaveID = -1;
---@type GameSaveData 功能缓存
SaveData.temp = {};

function SaveData:ctor()
    self.AutoSave = {};
    self.PlayerData = {};
    self.SettingData = {};
    self.SaveDataList = {};
end

function SaveData:SetPlayerData(info)
    self.PlayerData = info
end

function SaveData:SetSettingData(info)
    self.SettingData = info
end

function SaveData:SetAutoData(info)
    self.AutoSave = info
end

function SaveData:SetSaveDataList(info)
    self.SaveDataList = info
end

function SaveData:UpdateAutoSave()
    self.AutoSave = GameSaveData.new();
    self.AutoSave:UpdateNewSave("AutoSave", self.AutoSaveID)
    self.temp = self.AutoSave;
end

function SaveData:SetBattleData(info)
    self.temp.SaveBattleData = info
end

function SaveData:SetRecruitSoliderData(info)
    self.temp.RecruitSoliderData = info
end

function SaveData:SetRecruitTankData(info)
    self.temp.RecruitTankData = info
end

function SaveData:SetBattleTeamData(info)
    self.temp.BattleTeamData = info
end

function SaveData:SetDataList(id, name)
    if self.SaveDataList[tonumber(id)] ~= nil then
        self.temp = self.SaveDataList[id];
        self.temp:UpdateOldSave();
    else
        local tempSave = GameSaveData.new();
        tempSave:UpdateNewSave(name, id)
        self.SaveDataList[tonumber(id)] = tempSave;
        self.temp = tempSave
    end
end

function SaveData:CleanTemp()
    self.temp = {};
end

return SaveData
