-----
----- Generated by EmmyLua(https://github.com/EmmyLua)
----- Created by JCY.
----- DateTime: 2018/10/10 11:18
-----

local PlayerData = require("Game.Main.Model.Data.PlayerData")
local SaveModel = require("Game.Main.Model.SaveModel")

---@class PlayerDataModel:ISaveLoad
local PlayerDataModel = {};
local this = PlayerDataModel;

---@type PlayerData 玩家信息
PlayerDataModel.PlayerData = {};

function PlayerDataModel.Load(info)
    this.PlayerData = PlayerData.new();
    if info~= nil  then
        this.PlayerData:UpdateInfo(info.PlayerData);
    end
end

function PlayerDataModel.Save()
    SaveModel.SaveData:SetPlayerData(this.PlayerData);
end

function PlayerDataModel.InitPlayerData(name)
    this.PlayerData:InitPlayerData(name);
end

function PlayerDataModel.SetPlayerIcon(index)
    this.PlayerData:SetPlayerIcon(index)
end

function PlayerDataModel.SetRectentPlayTime()
    this.PlayerData:SetRectentPlayTime()
end

function PlayerDataModel.SetRectentQuitTime()
    this.PlayerData:SetRectentQuitTime()
end

function PlayerDataModel.SetRectentSaveGameTime()
    this.PlayerData:SetRectentSaveGameTime();
end

function PlayerDataModel.SetRectentPlaySaveID(index)
    this.PlayerData:SetRectentPlaySaveID(index)
end

function PlayerDataModel.SetPlayerIcon(index)
    this.PlayerData:SetPlayerIcon(index);
end

function PlayerDataModel.SetGameTime()
    this.PlayerData:SetGameTime();
end

function PlayerDataModel.GetGameTime()
    return this.PlayerData.GameTime;
end

function PlayerDataModel.GetPlayerName()
    return this.PlayerData.Name;
end

function PlayerDataModel.GetRectentPlaySaveID()
    return this.PlayerData.RectentPlaySaveID
end

function PlayerDataModel.GetPlayerIcon()
    return this.PlayerData.PlayerIcon;
end

return PlayerDataModel;