---
---Lua字符串扩展方法,使用Lua自身的扩展方法
---Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JCY.
--- DateTime: 2018/10/10 13:53
---

local bit = require "bit"

local lshift = bit.lshift
local rshift = bit.rshift
local bxor = bit.bxor

local byte = string.byte
local sub = string.sub
local len = string.len

--获取字符串HASH
---@param  str InputStr
function StrHash(str)
    local l = len(str)
    local h = l
    local step = rshift(l, 5) + 1
    for i = l, step, -step do
        h = bxor(h, (lshift(h, 5) + byte(sub(str, i, i)) + rshift(h, 2)))
    end
    return h
end
