---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JCY.
--- DateTime: 2018/10/19 11:48
---

---@class LoginState:IGameState 登录相关的游戏状态
local LoginState = {}
local this = LoginState;

function LoginState.OnEnter()

end

function LoginState.Update()

end

function LoginState.OnExit()

end

return LoginState;