---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JCY.
--- DateTime: 2018/10/18 19:38
---

---@class ISaveLoad
local ISaveLoad = {}

---存储方法
function ISaveLoad.Save()

end

---读取方法
function ISaveLoad.Load()

end

return ISaveLoad