//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Assets_Scripts_Game_Launcher_Task_LuaHandoverTaskWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Assets.Scripts.Game.Launcher.Task.LuaHandoverTask), typeof(System.Object));
		L.RegFunction("StartTask", StartTask);
		L.RegFunction("AddTask", AddTask);
		L.RegFunction("Lanuch", Lanuch);
		L.RegFunction("New", _CreateAssets_Scripts_Game_Launcher_Task_LuaHandoverTask);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Weight", get_Weight, null);
		L.RegVar("SetTaskProgress", get_SetTaskProgress, set_SetTaskProgress);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateAssets_Scripts_Game_Launcher_Task_LuaHandoverTask(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				Assets.Scripts.Game.Launcher.Task.LuaHandoverTask obj = new Assets.Scripts.Game.Launcher.Task.LuaHandoverTask();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: Assets.Scripts.Game.Launcher.Task.LuaHandoverTask.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StartTask(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Assets.Scripts.Game.Launcher.Task.LuaHandoverTask obj = (Assets.Scripts.Game.Launcher.Task.LuaHandoverTask)ToLua.CheckObject<Assets.Scripts.Game.Launcher.Task.LuaHandoverTask>(L, 1);
			obj.StartTask();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddTask(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Assets.Scripts.Game.Launcher.Task.LuaHandoverTask obj = (Assets.Scripts.Game.Launcher.Task.LuaHandoverTask)ToLua.CheckObject<Assets.Scripts.Game.Launcher.Task.LuaHandoverTask>(L, 1);
			LuaTable arg0 = ToLua.CheckLuaTable(L, 2);
			obj.AddTask(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Lanuch(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Assets.Scripts.Game.Launcher.Task.LuaHandoverTask obj = (Assets.Scripts.Game.Launcher.Task.LuaHandoverTask)ToLua.CheckObject<Assets.Scripts.Game.Launcher.Task.LuaHandoverTask>(L, 1);
			obj.Lanuch();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Weight(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Assets.Scripts.Game.Launcher.Task.LuaHandoverTask obj = (Assets.Scripts.Game.Launcher.Task.LuaHandoverTask)o;
			int ret = obj.Weight;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Weight on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_SetTaskProgress(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Assets.Scripts.Game.Launcher.Task.LuaHandoverTask obj = (Assets.Scripts.Game.Launcher.Task.LuaHandoverTask)o;
			System.Action<XQFramework.Laucher.ILanucherTask,float,string> ret = obj.SetTaskProgress;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index SetTaskProgress on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_SetTaskProgress(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Assets.Scripts.Game.Launcher.Task.LuaHandoverTask obj = (Assets.Scripts.Game.Launcher.Task.LuaHandoverTask)o;
			System.Action<XQFramework.Laucher.ILanucherTask,float,string> arg0 = (System.Action<XQFramework.Laucher.ILanucherTask,float,string>)ToLua.CheckDelegate<System.Action<XQFramework.Laucher.ILanucherTask,float,string>>(L, 2);
			obj.SetTaskProgress = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index SetTaskProgress on a nil value");
		}
	}
}

