//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Assets_Framework_Lua_LuaUi_LuaUiWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Assets.Framework.Lua.LuaUi.LuaUi), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("Initialize", Initialize);
		L.RegFunction("GetField", GetField);
		L.RegFunction("GetFields", GetFields);
		L.RegFunction("ManulAddEvent", ManulAddEvent);
		L.RegFunction("InitLife", InitLife);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("FileName", get_FileName, set_FileName);
		L.RegVar("PrefabPath", get_PrefabPath, set_PrefabPath);
		L.RegVar("Fields", get_Fields, set_Fields);
		L.RegVar("Events", get_Events, set_Events);
		L.RegVar("Life", get_Life, set_Life);
		L.RegVar("BindingTable", get_BindingTable, set_BindingTable);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Initialize(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			Assets.Framework.Lua.LuaUi.LuaUi obj = (Assets.Framework.Lua.LuaUi.LuaUi)ToLua.CheckObject<Assets.Framework.Lua.LuaUi.LuaUi>(L, 1);
			LuaTable arg0 = ToLua.CheckLuaTable(L, 2);
			LuaTable arg1 = ToLua.CheckLuaTable(L, 3);
			obj.Initialize(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetField(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Assets.Framework.Lua.LuaUi.LuaUi obj = (Assets.Framework.Lua.LuaUi.LuaUi)ToLua.CheckObject<Assets.Framework.Lua.LuaUi.LuaUi>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			UnityEngine.Object o = obj.GetField(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetFields(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Assets.Framework.Lua.LuaUi.LuaUi obj = (Assets.Framework.Lua.LuaUi.LuaUi)ToLua.CheckObject<Assets.Framework.Lua.LuaUi.LuaUi>(L, 1);
			LuaTable arg0 = ToLua.CheckLuaTable(L, 2);
			obj.GetFields(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ManulAddEvent(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Assets.Framework.Lua.LuaUi.LuaUi obj = (Assets.Framework.Lua.LuaUi.LuaUi)ToLua.CheckObject<Assets.Framework.Lua.LuaUi.LuaUi>(L, 1);
			LuaTable arg0 = ToLua.CheckLuaTable(L, 2);
			obj.ManulAddEvent(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int InitLife(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Assets.Framework.Lua.LuaUi.LuaUi obj = (Assets.Framework.Lua.LuaUi.LuaUi)ToLua.CheckObject<Assets.Framework.Lua.LuaUi.LuaUi>(L, 1);
			LuaTable arg0 = ToLua.CheckLuaTable(L, 2);
			obj.InitLife(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_FileName(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Assets.Framework.Lua.LuaUi.LuaUi obj = (Assets.Framework.Lua.LuaUi.LuaUi)o;
			string ret = obj.FileName;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index FileName on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PrefabPath(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Assets.Framework.Lua.LuaUi.LuaUi obj = (Assets.Framework.Lua.LuaUi.LuaUi)o;
			string ret = obj.PrefabPath;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index PrefabPath on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Fields(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Assets.Framework.Lua.LuaUi.LuaUi obj = (Assets.Framework.Lua.LuaUi.LuaUi)o;
			System.Collections.Generic.List<Assets.Framework.Lua.LuaUi.LuaUi.LuaUiField> ret = obj.Fields;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Fields on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Events(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Assets.Framework.Lua.LuaUi.LuaUi obj = (Assets.Framework.Lua.LuaUi.LuaUi)o;
			System.Collections.Generic.List<Assets.Framework.Lua.LuaUi.LuaUi.LuaUiEvent> ret = obj.Events;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Events on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Life(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Assets.Framework.Lua.LuaUi.LuaUi obj = (Assets.Framework.Lua.LuaUi.LuaUi)o;
			Assets.Framework.Lua.LuaUi.LuaUi.LuaUiLife ret = obj.Life;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Life on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BindingTable(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Assets.Framework.Lua.LuaUi.LuaUi obj = (Assets.Framework.Lua.LuaUi.LuaUi)o;
			LuaInterface.LuaTable ret = obj.BindingTable;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index BindingTable on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_FileName(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Assets.Framework.Lua.LuaUi.LuaUi obj = (Assets.Framework.Lua.LuaUi.LuaUi)o;
			string arg0 = ToLua.CheckString(L, 2);
			obj.FileName = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index FileName on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_PrefabPath(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Assets.Framework.Lua.LuaUi.LuaUi obj = (Assets.Framework.Lua.LuaUi.LuaUi)o;
			string arg0 = ToLua.CheckString(L, 2);
			obj.PrefabPath = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index PrefabPath on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Fields(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Assets.Framework.Lua.LuaUi.LuaUi obj = (Assets.Framework.Lua.LuaUi.LuaUi)o;
			System.Collections.Generic.List<Assets.Framework.Lua.LuaUi.LuaUi.LuaUiField> arg0 = (System.Collections.Generic.List<Assets.Framework.Lua.LuaUi.LuaUi.LuaUiField>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.List<Assets.Framework.Lua.LuaUi.LuaUi.LuaUiField>));
			obj.Fields = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Fields on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Events(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Assets.Framework.Lua.LuaUi.LuaUi obj = (Assets.Framework.Lua.LuaUi.LuaUi)o;
			System.Collections.Generic.List<Assets.Framework.Lua.LuaUi.LuaUi.LuaUiEvent> arg0 = (System.Collections.Generic.List<Assets.Framework.Lua.LuaUi.LuaUi.LuaUiEvent>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.List<Assets.Framework.Lua.LuaUi.LuaUi.LuaUiEvent>));
			obj.Events = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Events on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Life(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Assets.Framework.Lua.LuaUi.LuaUi obj = (Assets.Framework.Lua.LuaUi.LuaUi)o;
			Assets.Framework.Lua.LuaUi.LuaUi.LuaUiLife arg0 = (Assets.Framework.Lua.LuaUi.LuaUi.LuaUiLife)ToLua.CheckObject<Assets.Framework.Lua.LuaUi.LuaUi.LuaUiLife>(L, 2);
			obj.Life = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Life on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_BindingTable(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Assets.Framework.Lua.LuaUi.LuaUi obj = (Assets.Framework.Lua.LuaUi.LuaUi)o;
			LuaTable arg0 = ToLua.CheckLuaTable(L, 2);
			obj.BindingTable = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index BindingTable on a nil value");
		}
	}
}

