//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class SaveManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(SaveManager), typeof(System.Object));
		L.RegFunction("IsPlayData", IsPlayData);
		L.RegFunction("LoadSave", LoadSave);
		L.RegFunction("DoSave", DoSave);
		L.RegFunction("New", _CreateSaveManager);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Instance", get_Instance, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateSaveManager(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				SaveManager obj = new SaveManager();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: SaveManager.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IsPlayData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			SaveManager obj = (SaveManager)ToLua.CheckObject<SaveManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			bool o = obj.IsPlayData(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadSave(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			SaveManager obj = (SaveManager)ToLua.CheckObject<SaveManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			System.Action<object> arg1 = (System.Action<object>)ToLua.CheckDelegate<System.Action<object>>(L, 3);
			obj.LoadSave(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DoSave(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			SaveManager obj = (SaveManager)ToLua.CheckObject<SaveManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			object arg1 = ToLua.ToVarObject(L, 3);
			obj.DoSave(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Instance(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, SaveManager.Instance);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

