//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class TankRadarMapWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(TankRadarMap), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("InjectMap", InjectMap);
		L.RegFunction("Test", Test);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("map", get_map, set_map);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int InjectMap(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 4);
			TankRadarMap obj = (TankRadarMap)ToLua.CheckObject<TankRadarMap>(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			float arg1 = (float)LuaDLL.luaL_checknumber(L, 3);
			float arg2 = (float)LuaDLL.luaL_checknumber(L, 4);
			obj.InjectMap(arg0, arg1, arg2);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Test(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			TankRadarMap obj = (TankRadarMap)ToLua.CheckObject<TankRadarMap>(L, 1);
			obj.Test();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_map(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			TankRadarMap obj = (TankRadarMap)o;
			SpringGUI.RadarMap ret = obj.map;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index map on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_map(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			TankRadarMap obj = (TankRadarMap)o;
			SpringGUI.RadarMap arg0 = (SpringGUI.RadarMap)ToLua.CheckObject<SpringGUI.RadarMap>(L, 2);
			obj.map = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index map on a nil value");
		}
	}
}

