//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace Assets.Tools.Script.Sound
{
    /// <summary>
    /// 播放一个效果音
    /// </summary>
	public class EffectSoundPlayer
	{
        /// <summary>
        /// 用默认的effectSound播放声音
        /// </summary>
        /// <param name="clip"></param>
        /// <returns></returns>
        static public AudioSource PlaySound(AudioClip clip)
        {
            //return NGUITools.PlaySound(clip, ClientGame.Data.playerData.playerSetting.effectSound);
            return SoundUtilities.PlaySound(clip, SoundUtilities.volumeCentre.effectSound, false, null);
        }
        static public void StopSound(AudioSource audioSource)
        {
            SoundUtilities.StopSound(audioSource);
        }
        /// <summary>
        /// 用默认的effectSound*volume播放声音
        /// </summary>
        /// <param name="clip"></param>
        /// <param name="volume"></param>
        /// <returns></returns>
        static public AudioSource PlaySound(AudioClip clip, float volume)
        {
            //return NGUITools.PlaySound(clip, ClientGame.Data.playerData.playerSetting.effectSound);
            return SoundUtilities.PlaySound(clip, SoundUtilities.volumeCentre.effectSound*volume, false, null);
        }
	}
}

